# Generated by Django 5.2 on 2026-01-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0002_run_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('init', 'Забег инициализирован'), ('in_progress', 'Забег начат'), ('finished', 'Забег закончен')], default='init', max_length=50),
        ),
    ]
